version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: ./developer_server.sh start
            . venv/bin/activate
            python manage.py test

      # TODO: run tests checking for:-
      #   - plugin build output
      #   - styling selenium + headless chrome
      #   - spaelleng mistaeks
      #   - vulgarities left in as a byproduct of a debbuging session gone wild
      #- run:
      #    name: run tests
      #    command: |
      #      . venv/bin/activate
      #      python manage.py test


  ghp_deploy:
    steps:
      - run:
          name: deploy to github
          command: ghp-import -p -f output -m `git log --format=%B -n 1 $CIRCLE_SHA1`

workflows:
  version: 2
  ci:
    jobs:
      - build
      - ghp_deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
